### ISSUE TITLE
Creating an environment named `production` fails 

### ISSUE THREAD

**Issue by laugmanuel** [theforeman/foreman_puppet#142]
When creating a new Puppet environment named `production`, the creation fails:
![image](https://user-images.githubusercontent.com/5444009/118264408-f0638180-b4b7-11eb-902e-9c6c4b4c1bf3.png)

The environment does indeed exist if I check using `rake console` - the GUI seems to not show it:
```ruby
[5] pry(main)> Environment.all
=> [#<Environment:0x00007fa76b654fe0
  id: 1,
  name: "production",
  created_at: Fri, 14 May 2021 11:07:45 UTC +00:00,
  updated_at: Fri, 14 May 2021 11:07:45 UTC +00:00>]
```

URL: `http://localhost:5000/foreman_puppet/environments`
Foreman branch: `2.5-stable`
Plugin: `master`

**Comment by ezr-ondrej** [comment]
Did you run the plugin migrations? There was an issue with taxonomies still referring to the core Environment class, which should be fixed by  https://github.com/theforeman/foreman_puppet/blob/830fd280fd5b57e146211786474ecd8645a43cfe/db/migrate/20200720123005_migrate_puppet_core_types.foreman_puppet.rb#L8

**Comment by ezr-ondrej** [comment]
Could you try `bundle exec rails db:migrate VERSION=0 SCOPE=foreman_puppet` and `bundle exec rails db:migrate SCOPE=foreman_puppet` ?

**Comment by laugmanuel** [comment]
I'll retest this with a clean database.
I thought I ran the migrations prior. However, after reverting to VERSION=0 and running them again, the environment shows up.

**Comment by laugmanuel** [comment]
Indeed, this seems like a problem on my end. With a fresh database everything works as expected.
I'll close this.
