### ISSUE TITLE
Redirect core routes to use plugin routes

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#152]
Refers to https://github.com/theforeman/foreman_puppet/pull/151#issuecomment-851874564 .

As of now, old API routes are still active. 
```
[I|app|e93963d1] Started GET "/api/puppetclasses" for 192.168.121.1 at 2021-06-01 06:45:45 +0000$
[I|app|e93963d1] Processing by Api::V2::PuppetclassesController#index as JSON
```
Two possibilities:
1) redirect the routes for now (seems easier in terms of implementation and more user friendly for current API users) 
2) disable routes (we be done eventually, even if we implement the redirection for now)

**Comment by nadjaheitmann** [comment]
Personally, I think alternative 1 is more in line with the transition strategy that we currently try to follow.

**Comment by nadjaheitmann** [comment]
I have looked into this. Is there a way to have the re-routing in the plugin directly? For `statistic and trends` the plugin route is set in Foreman core: https://github.com/theforeman/foreman/blob/2.5-stable/config/routes/api/v2.rb#L208

Shall we do the same for Puppet?

**Comment by timogoebel** [comment]
> Is there a way to have the re-routing in the plugin directly?

I believe it should be possible to override core routes in the plugin, see something like this: http://www.marcelofossrj.com/recipe/2018/08/22/engines-routes.html (look for `routes.prepend`).
