### ISSUE TITLE
Configure --> Puppet ENC menu inconsistent

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#159]
There is a menu entry `Puppet` in `Configure` where `Environments` can be chosen (link leads to core controller).
The `Environments` entry for `Puppet ENC` is missing.

Tested on my Forklift with 
foreman_puppet master (6f811b1fa8fe4ebff1b7e68e39ebe116cb4b617f) 
foreman 2.5-stable (e880002a8edff382cb53ffea136d2e527132df13)

![path821](https://user-images.githubusercontent.com/71487468/123066982-d9964000-d410-11eb-81ef-c808d9e5dccc.png)

**Comment by nadjaheitmann** [comment]
It looks just fine if Puppet is extracted. Is this worth fixing at all?

**Comment by ezr-ondrej** [comment]
If it's ok with extracted Puppet, then probably no, as this would need to be fixed in plugin and released as new version.
I wonder why that is though, it works for me on develop branch, so it is bit weird behaviour :(
