### ISSUE TITLE
Push 1.0.0.rc.1 tag

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman_puppet#168]
On https://rubygems.org/gems/foreman_puppet there's a 1.0.0.rc.1 gem but this isn't present in git. It's a good practice to have them match.

**Comment by timogoebel** [comment]
@ezr-ondrej: Do you mind taking care of this? Thanks.

**Comment by ezr-ondrej** [comment]
Thanks for noticing @ekohl, but I'm not sure what do you mean. We are still on pre in master, I'll bump that to next version.pre, but we have `1.0.0.rc.1` tag, and we have branch `1.0-stable` that cointains the current version.
From my experience having master on last released version is wrong, it should be next release version, especially with plugins, that might want to require freshly merged funcionality of other plugin, thus might want to know what is the next version.

**Comment by ekohl** [comment]
Ah, I guess I was confused because eab57b72349ed148f2c785884d4ad8c205dd758a isn't part of master.
