### ISSUE TITLE
Smart proxy apidoc inconsistency

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#171]
Environments and smart proxies both have the same API endpoint for importing puppet classes. I tried to prepend the `smart_proxy` path with `foreman_puppet' for #170 but so far no success. It is a bit tricky because it is defined as concern. Any ideas?

![image](https://user-images.githubusercontent.com/71487468/126645997-735a252d-328d-4cb0-bf33-5c0da4826967.png)
![image](https://user-images.githubusercontent.com/71487468/126646054-0e6b8d42-c13c-4750-858e-009956140557.png)

**Comment by timogoebel** [comment]
> It is a bit tricky because it is defined as concern.

If I get this correctly, both the Environment and Smart Proxy models (defined in core) are extended by this plugin.
I believe the proper rails way would be to not use a scope for this in the routes as the controllers that handle the requests are core controllers (that are just extended a bit).

**Comment by nadjaheitmann** [comment]
> If I get this correctly, the Smart Proxy model (defined in core) is extended by this plugin.

Exactly. But the main functionality of this is done by the plugin rather than by core. The routes are handled by the `environments` controller. The corresponding routes in core have been deprecated and there is a deprecation warning. 

> I believe the proper rails way would be to not use a scope for this in the routes 

What exactly do you mean? Not using `foreman_puppet` prefix for the routes at all?

**Comment by ezr-ondrej** [comment]
> What exactly do you mean? Not using `foreman_puppet` prefix for the routes at all?

I think it is the best option for these routes, given they are on smart_proxies namespace, there is no point in prefixing them. It was a wrong decisition by me.

**Comment by nadjaheitmann** [comment]
I see. If this is the case, do we need to keep the routes within the Puppet environment at all? Will it break anything if we remove them? I think, Hammer should be fine, not sure about FAM (https://github.com/theforeman/foreman-ansible-modules/blob/develop/plugins/modules/puppetclasses_import.py). 

In any case, the deprecation warning for the route needs to go.
