### ISSUE TITLE
foreman_puppet/app/models/foreman_puppet/host_puppet_facet.rb: parent_config_groups() should not return 'nil'

### ISSUE THREAD

**Issue by pkranenburg** [theforeman/foreman_puppet#206]
source: foreman_puppet/app/models/foreman_puppet/host_puppet_facet.rb, line51.
method parent_config_groups() should not return a nil value, since that results in an exception in callers. This happens in the puppet node classifier code path whenever a hostgroup is encountered that does not have any puppet plugin data.

The patch indicated below fixes this issue.

```
    def parent_config_groups
          return [] unless host.hostgroup
          host.hostgroup.puppet&.all_config_groups || []
                                                   ^^^^^^
    end
```

**Comment by ezr-ondrej** [comment]
Thanks for the debugging?
Would you mind to send a patch?
