### ISSUE TITLE
`Puppet Environment` column missing on Hosts page

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#210]
Details see here: https://community.theforeman.org/t/foreman-3-0-environment-column-nao-available-on-hosts-page/25720/4

**Comment by ezr-ondrej** [comment]
I'd first want to hear what is the issue for the user, as I do not believe the column is as important to add deface...
We want to stay close to what we had, but not the same.

**Comment by nadjaheitmann** [comment]
Agreed. Let's wait for the user and also see if other users request this, eventually.

**Comment by jadestorm** [comment]
I'll chime in and say I did occasionally find that column handy -- but it's in way a dealbreaker for me.

**Comment by mattttv** [comment]
this is a very important column for us - could you please bring it back?

**Comment by damnitdom** [comment]
Can you please bring this back or give us an option to add it back.

**Comment by ezr-ondrej** [comment]
This is not easy to do without little bit of hacking. Could some of you guys elaborate in the discourse thread on why is this column important in your usecase?

**Comment by jadestorm** [comment]
I edited my comment above since I typoed something  LOL  it's FAR from a dealbreaker for me but I worded it as if it was.  The few times I've used it was to frankly catch a few one-off hosts that I had switched their environment for testing and forgotten to switch it back.  So it was occasionally handy, not worth hacking in from my perspective.  If it were a simple matter, then sure.  But if it's a pain, I've got no problem skipping it.

I'm probably not the target audience for the question given I "don't care"  lol  but figured I'd chime in with my use case if it's helpful,

**Comment by nadjaheitmann** [comment]
We don't actually mind bringing this back as there is already a PR for this. However, we would love to hear why this column is so important that we should bring it back in the first place. So thanks @jadestorm for giving some insight. Would be nice if @mattttv @damnitdom could share their opinion as well :)

**Comment by laugmanuel** [comment]
I can also report very frequent usage of the column in our current environment.

We do change the puppet environment for many hosts quite frequently (sometimes multiple times a day). The column serves as a fast way to see the current status of the hosts and which still need to be changed back to their regular environment. This also helps to see if one/multiple hosts are currently being used for testing (as this often includes changing their environment to a different one).

Searching for hosts based on environment is possible, but you first need to know what to search for. 😉

**Comment by nadjaheitmann** [comment]
Thanks @laugmanuel , this is what I call helpful :)

**Comment by timogoebel** [comment]
@ezr-ondrej: Instead of adding deface to add the column, couldn't we add a small extension point in core?

**Comment by ezr-ondrej** [comment]
@timogoebel yup, I'd prefer that, that sounds like a reasonable solution. We still have [pagelets](https://github.com/theforeman/foreman/blob/d6c44dcf85424da80f8d9d4de5bf9c0f57b19a10/app/helpers/pagelets_helper.rb#L13), so we can use them :+1: We will have to add two (one for header and other for the data column itself), but better then Deface IMO.
@nadjaheitmann how does that sound?

**Comment by nadjaheitmann** [comment]
We can give it a try. @ezr-ondrej Do you have an example code for that?

**Comment by ezr-ondrej** [comment]
Examples: https://github.com/theforeman/foreman/search?q=render_pagelets_for
There is nothing for tables , but [smart_proxies/show](https://github.com/theforeman/foreman/blob/69379b51a33344de93836950565ecbfae0c4df23/app/views/smart_proxies/show.html.erb#L100) is quite close. We will need two entry points (one in [header](https://github.com/theforeman/foreman/blob/69379b51a33344de93836950565ecbfae0c4df23/app/views/hosts/_list.html.erb#L15) and another in the [body](https://github.com/theforeman/foreman/blob/69379b51a33344de93836950565ecbfae0c4df23/app/views/hosts/_list.html.erb#L36) )

**Comment by nadjaheitmann** [comment]
Thank you, I will have a look at that and then modify #216  :+1:

**Comment by mattttv** [comment]
> We don't actually mind bringing this back as there is already a PR for this. However, we would love to hear why this column is so important that we should bring it back in the first place. So thanks @jadestorm for giving some insight. Would be nice if @mattttv @damnitdom could share their opinion as well :)

hello @laugmanuel!
our use case is as follows - we use the frontpage of foreman showing all or some of our hosts. The environment column (puppet environment) gave us a quick hint what hosts are affected on a certain git push (stable environment uses different git-branch than development environment). Right now we have to look through each host to find that out or use hammer which is worse than just having a column.
Kind Regards and thank you very much,
Matt

**Comment by dwjvaughan** [comment]
Just adding my thoughts as I raised this in the Foreman forum - it was a very handy column for us too, for much the same reasons as @mattttv. Being able to see the puppet environment at-a-glance was great as sometimes you may lose track of which env you assigned a node to. Foreman is our only real way of visualising things too, as our entire puppet infra is containerised.
