### ISSUE TITLE
 Hostgroups “nest” error 

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#219]
https://community.theforeman.org/t/hostgroups-nest-error/25811

**Comment by ezr-ondrej** [comment]
Duplicate of #189

**Comment by nadjaheitmann** [comment]
Technically, it is still an open issue for foreman_puppet v1, isn't it ;)

**Comment by ezr-ondrej** [comment]
well it's not released, but it is resolved :)
And it's a dup nevertheless :)
