### ISSUE TITLE
"Organization admin" role doesn’t have permission to edit host’s Puppet classes

### ISSUE THREAD

**Issue by hseagle2015** [theforeman/foreman_puppet#244]
<div class="cooked"><p><strong>Problem:</strong><br>
User assigned with “Organization admin” role doesn’t have permission to edit Puppet classes associated with specific host.</p>
<p>Logged in as user with “Organization admin” role, navigate to Hosts 
&gt; [example_host] &gt; Edit &gt; Puppet ENC. Adding new or removing 
existing Puppet classes isn’t possible. The following message appears 
when hovering over classes: “Not authorized to edit classes”</p>
<p>Adding and removing config groups works fine.</p>
<p><strong>Expected outcome:</strong><br>
The user shouldn’t receive the “Not authorized to edit classes” message and it should be able to add/remove Puppet classes.</p>
<p><strong>Foreman and Proxy versions:</strong><br>
3.1.0</p>
<p><strong>Foreman and Proxy plugin versions:</strong></p>
<div class="md-table">

Plugin | Version
-- | --
foreman_memcache | 0.1.1
foreman_puppet | 2.0.0
foreman_templates | 9.1.0
foreman_vault | 1.1.0
puppetdb_foreman | 5.0.0

</div><p><strong>Distribution and version:</strong><br>
CentOS Linux release 7.9.2009 (Core)</p>

**Other relevant data:**
“Organization admin” role is assigned with `edit_classes` filter for HostClass resource type, which should allow adding/removing of Puppet 
classes.</p></div>

The user is associated with specific organization and location (the same organization and location in which the host is “located”).

I'm experiencing the same problem if the user is assigned with the "Manager" role.

**Comment by ares** [comment]
I can confirm the permission is there but it does not have the desired effect.

**Comment by ezr-ondrej** [comment]
Thanks for reporting @hseagle2015 ! I'm fixing it in #251 if you could try that it fixes your issue, it would be appreciated.

**Comment by hseagle2015** [comment]
@ezr-ondrej I'm not too familiar with foreman_puppet plugin. Can I patch my existing foreman_puppet installation? I see that the changes are minimal.

Do I have to run additional command for the `db/migrate/20220201205305_migrate_host_class_permission.foreman_puppet.rb` to take effect or will that migration happen automatically once I restart Foreman (or when Foreman loads the plugin)?

**Comment by ezr-ondrej** [comment]
Hi, patching the plugin is quite straight forward once you locate it. On Centos 7 it should be in `/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_puppet-2.0.1`

Then you can `curl https://patch-diff.githubusercontent.com/raw/theforeman/foreman_puppet/pull/251.patch | patch -p1` and restart foreman. The migration will not be applied, but that is not the important part :)

**Comment by hseagle2015** [comment]
Mine is actually in `/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_puppet-2.0.0` (one point-release lower than yours). I'm also using CentOS 7 and the plugin is installed from foreman-plugins yum repo.

I'll try to patch it tomorrow and check if I can reproduce the problem. If I should update the plugin to v2.0.1 first please let me know where I can find that release. I didn't find it among the [nightly packages](https://yum.theforeman.org/plugins/nightly/el7/x86_64/).

**Comment by ezr-ondrej** [comment]
Oh, yeah I have a custom build, but the minor version doesn't matter, the differences are unsignificant, and once we release a new version of the plugin (hopefully including this fix) your local changes will be overriden, so it should be fine :+1:

**Comment by hseagle2015** [comment]
@ezr-ondrej I'm glad to report that your fix works on my end and it resolved the problem I reported. Thank you very much for your effort :beers:
