### ISSUE TITLE
Last config status on reports tab

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#264]

**Comment by Ron-Lavi** [comment]
@marisvirik HI, during the puppet sync meeting, we mentioned this card needs some redesign :)

**Comment by MariSvirik** [comment]
Updated mocks: https://marvelapp.com/prototype/d45i26d/screen/83999717
@Manisha15 @Ron-Lavi

**Comment by nadjaheitmann** [comment]
@MariSvirik @Manisha15 and myself don't have permission to view this. Can you please share again?

**Comment by MariSvirik** [comment]
@nadjaheitmann @Manisha15 so, we ditched Marvel as a tool for sharing almost a year ago and I don't even have access anymore. Let me see if I can find it in my files.

**Comment by MariSvirik** [comment]
Check this. I guess it should be what you are looking for: https://www.sketch.com/s/797a8018-3119-4445-8cb0-a744261a9eb5

**Comment by nadjaheitmann** [comment]
Thanks. Do I need to sign up for that page?

**Comment by nadjaheitmann** [comment]
Don't think that I can just access that. Do you have any other possibility to share the document?

**Comment by MariSvirik** [comment]
I think you need to create an account to view it. I send you an invite. 
The only other option is to add screenshots here.

**Comment by nadjaheitmann** [comment]
I created an account with another a-mail address. I asked for permission on sketch. Problem with the platform is that this needs a subscription, eventually.

**Comment by MariSvirik** [comment]
If you are not going to edit it, it shouldn't be needed. I haven't received any requests.
<img width="731" alt="Screenshot 2023-10-27 at 16 00 38" src="https://github.com/theforeman/foreman_puppet/assets/51960547/e07d582f-fa86-4861-ad21-0f6a39650e2c">
<img width="727" alt="Screenshot 2023-10-27 at 16 00 11" src="https://github.com/theforeman/foreman_puppet/assets/51960547/f5cdb19d-1a78-4df1-93a3-6a5fb2d02cd0">
. 
Trying to import it to Figma ( a new tool we are going to use), but I have some problems with that right now.

**Comment by nadjaheitmann** [comment]
Thanks @MariSvirik for sharing the screen shots. Are there also mocks for the other Puppet tags like `Assigned classes` and `Smart class parameters`?

Let us know if you manage the import for the other tool. For me, still no success with sketch.

**Comment by MariSvirik** [comment]
![Puppet tab -expanded](https://github.com/theforeman/foreman_puppet/assets/51960547/e53be0a4-3fdb-440b-a667-fca1c89f2758)
![puppet tab = reports option with divider copy](https://github.com/theforeman/foreman_puppet/assets/51960547/4a79ab3c-a5f5-48ab-9819-cce7e06eebfa)![Puppet Classes](https://github.com/theforeman/foreman_puppet/assets/51960547/517b5192-8c32-4f28-a973-a1e2d179cec9)
![Puppet Classes interaction](https://github.com/theforeman/foreman_puppet/assets/51960547/312613d5-1d40-440d-b202-35ddb6dbb612)
![Puppet Smart classes parameters](https://github.com/theforeman/foreman_puppet/assets/51960547/58f64fb7-f7cd-4af4-bdf4-3bba5267c929)
![Puppet Smart classes parameters  interaction](https://github.com/theforeman/foreman_puppet/assets/51960547/8a673f07-96d9-44a6-8e8a-7edd1c7ccb3f)
![Puppet Smart classes parameters OVERRIDE](https://github.com/theforeman/foreman_puppet/assets/51960547/6807fe2d-702e-4920-9600-d97b528b5add)

**Comment by nadjaheitmann** [comment]
@stejskalleos I think we should bump a new version. Maybe a y version as this is a new feature. Let me know if I should do it.
