### ISSUE TITLE
Load ApplicationRecord explicitly early

### ISSUE THREAD

**Issue by Ron-Lavi** [theforeman/foreman_puppet#286]
https://community.theforeman.org/t/foreman-nightly-rpm-pipeline-1485-failed/28805/

After https://github.com/theforeman/foreman/pull/9050 got merged, puppet failed nightly :)

possible solutions @ezr-ondrej suggested:

> in that case it is about load order of Rails models, the migration loads LookupValue first.

>My guess (and be aware this is just working theory) is that classes named Something::Base make the Rails trip, as rails use Activerecord::Base inheritence in the algorithm to determine a table name, but without explicit namespace (so there is Base).
If there is another Base class in a scope of the class (like some Host class of ours, but also Nic, Facet), it may trip up the resolving of table_name, and if that trips the first time we’re resolving it for ApplicationRecord, then all models resolve their table name to application_records.

>Possible mitigations:
> 1) load ApplicationRecord explicitly early (this is bad for zetwerk, but at least it is only one specific class.
> 2) switch to Zeitwerk (which should resolve the namespace confusion), but we are not ready to do so just yet (I mean core is mostly ready, but plugins are not)

**Comment by nadjaheitmann** [comment]
This will be fixed in core for all plugins :)
