### ISSUE TITLE
Update graphql

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#288]
Soon, graphql will be updated in Foreman core and foreman_puppet needs some adjustments to properly work with it.

See https://github.com/theforeman/foreman_puppet/pull/285 for more details.

**Comment by nadjaheitmann** [comment]
@kamils-iRonin I saw that you did some GraphQL fixes. Do they solve this?

**Comment by kamils-iRonin** [comment]
@nadjaheitmann I think so. I will test the puppet Graphql api with Foreman 3.5 and let you know.

**Comment by kamils-iRonin** [comment]
@nadjaheitmann I just successfully tested GraphQL puppet (`master` branch) with Foreman (`3.5-stable` branch) using GraphiQL tool. I was able to fetch the environments and puppetclasses data and create a host that has the environment and puppetclasses assigned.

**Comment by nadjaheitmann** [comment]
> @nadjaheitmann I just successfully tested GraphQL puppet (`master` branch) with Foreman (`3.5-stable` branch) using GraphiQL tool. I was able to fetch the environments and puppetclasses data and create a host that has the environment and puppetclasses assigned.

@kamils-iRonin Thank you, sounds good! So we can close this issue, then?

**Comment by kamils-iRonin** [comment]
yes, we can 🙂 closing
