### ISSUE TITLE
Puppet reports page has a redundant origin column

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman_puppet#292]
On the reports page there is an origin column, but that feels redundant. I already selected Puppet -> Reports so it should only show Puppet reports.

![image](https://user-images.githubusercontent.com/155810/174607263-2211d535-bab7-45b8-ab7b-90ba9dae3ff2.png)

This is with foreman_puppet 4.0.1 on Foreman 3.3.0.

**Comment by Ron-Lavi** [comment]
That's true, it shouldn't be there :)

**Comment by Ron-Lavi** [comment]
merged in core
