### ISSUE TITLE
edit_environments and destroy_environments permissions is not working

### ISSUE THREAD

**Issue by laugmanuel** [theforeman/foreman_puppet#314]
We have many Puppet environments for specific use cases and we have multiple roles with the `*_environment` permissions to allow maintaining their own environments.

After migration to this plugin, the edit and destroy permission seem to be broken:
The UI shows only greyed-out environments with no menu option to delete them:
<img src="https://user-images.githubusercontent.com/5444009/199764915-5d6f2aaa-e589-4174-9ff5-4e4a33f134c4.png" width="40%">

I've created a user and role for testing this; the role is configured like that:
<img src="https://user-images.githubusercontent.com/5444009/199764327-87a2eba9-0708-4b61-8b2c-4ed653344648.png" width="40%">

The view, import and create permission seem to work fine -> removing them also removes the buttons/view.

**Comment by laugmanuel** [comment]
Is there any progress on this?

**Comment by nadjaheitmann** [comment]
I don't think so. Correct me if I am wring @Ron-Lavi I can try to have a look at this, eventually.

**Comment by nadjaheitmann** [comment]
@laugmanuel Which foreman and foreman_puppet versions are you at?

**Comment by nadjaheitmann** [comment]
By the way, have you tried to add filters for location and organization that allow `assign_location` and `assign_organization`? I think, this might also cause some problems because foreman_puppet is currently not well integrated with taxonomies.

**Comment by laugmanuel** [comment]
> @laugmanuel Which foreman and foreman_puppet versions are you at?

we're using a pretty old Foreman 3.1 and ForemanPuppet 2.0.7

**Comment by laugmanuel** [comment]
> By the way, have you tried to add filters for location and organization that allow `assign_location` and `assign_organization`? I think, this might also cause some problems because foreman_puppet is currently not well integrated with taxonomies.

I'll try to see if this makes anything better.

**Comment by nadjaheitmann** [comment]
> > @laugmanuel Which foreman and foreman_puppet versions are you at?
> 
> we're using a pretty old Foreman 3.1 and ForemanPuppet 2.0.7

Okay, I tried the additional permissions for Foreman 3.3+ and there it works.

**Comment by laugmanuel** [comment]
I've tested it locally again and it seems like the problem was fixed with Foreman 3.2 and/or ForemanPuppet 3.0.
With the old version (3.1 and ForemanPuppet 2.0), I could reproduce the bug.

I think we can close this

**Comment by laugmanuel** [comment]
Looking at the changes in Foreman core, I found: https://github.com/theforeman/foreman/pull/9118 This was indeed the cause for this.
