### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman_puppet#325]
This string can't be translated:
https://github.com/theforeman/foreman_puppet/blob/41ab916bbbc78cfdaff8fa7723df88165f31cbda/webpack/src/Components/Environments/Welcome.js#L13-L16

It's **always** invalid to use ```__(````.

_Originally posted by @ekohl in https://github.com/theforeman/foreman_puppet/pull/323#discussion_r1050737749_

**Comment by nadjaheitmann** [comment]
https://github.com/theforeman/foreman-tasks/pull/700 use this as reference to fix all problematic strings
