### ISSUE TITLE
Hammer plugin

### ISSUE THREAD

**Issue by ezr-ondrej** [theforeman/foreman_puppet#37]
https://github.com/amirfefer/hammer-cli-foreman-puppet

**Comment by nadjaheitmann** [comment]
I can work on the hammer plugin as well. 
> https://github.com/amirfefer/hammer-cli-foreman-puppet
Is this the current status?

**Comment by ezr-ondrej** [comment]
It would be awesome, if you could team up with @amirfefer on this.

Current status
----
There is a draft @ekohl started to clean up the core code prior it's removal, that would be great to finalize before moving to the plugin. Ewoud is saying he struggles to find time to finish it, so if you'd like to take that, that would be appreciated:
https://github.com/theforeman/smart-proxy/pull/771

@amirfefer recently resumed work on the plugin, so probably first asking him to push the recent changes prior to sending PRs, but his repo is indeed the primary develop repo as of now, before we move it under theforeman org.

**Comment by nadjaheitmann** [comment]
Thanks for the update. I will get in contact with @ekohl  and @amirfefer about the topics.

**Comment by ekohl** [comment]
@ezr-ondrej my PR is not really about hammer but really about the Smart Proxy modules.

**Comment by ezr-ondrej** [comment]
My bad, I've messed things up. Weren't there something similar for hammer, or am I just imagining stuff?

**Comment by nadjaheitmann** [comment]
Let me know if there is another PR that needs fixing before the Hammer plugin can move on. Right now, I am waiting for @amirfefer to provide some up-to-date information.

**Comment by ezr-ondrej** [comment]
Closing as it is in Done column but not closed
