### ISSUE TITLE
Host Details SubTabs Selector disappear during usage

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/foreman_puppet#374]
If I go on the Host Details `Puppet` tab and click on `ENC Preview`, I see the preview but the sub card selection disappears. 

![image](https://github.com/theforeman/foreman_puppet/assets/71487468/c182a17e-fc99-475c-9e50-01ab53a61dcb)

![image](https://github.com/theforeman/foreman_puppet/assets/71487468/4b9968eb-077e-441e-8507-8ea0a921be9d)

Also, if I expand `Puppet Details` on Reports Tab, the tab selector disappears as well. 

![image](https://github.com/theforeman/foreman_puppet/assets/71487468/7a5e493a-61d6-4b00-a31d-16b55de69da0)

**Comment by nadjaheitmann** [comment]
Update: I found that this is happening once the subtab becomes scrollable. 
@MariaAga Any idea how to fix this?

**Comment by MariaAga** [comment]
You can add `overflow: visible;` to the sub tab container `.pf-c-tabs .pf-m-secondary` and it should fix it from what I see.
Please add a specific class (like `puppet-host--tabs`) to the container and the css selector so it wont override anything else accidentally.

**Comment by nadjaheitmann** [comment]
Thanks, I opened #377
