### ISSUE TITLE
Search hosts by class from class UI issue with no class param

### ISSUE THREAD

**Issue by Patiphan-Thiansuwan** [theforeman/foreman_puppet#408]
We upgraded foreman from 2.3 to 3.10 then we encounter with issue similarly to this post 
https://github.com/theforeman/puppet-foreman/issues/1167#issue-2334642839

**Comment by nadjaheitmann** [comment]
Should have been fixed here: https://github.com/theforeman/foreman_puppet/commit/0835630aa4b92ec0cfe6429f5aa67e551e7a8b4e Which foreman_puppet version are you using?

**Comment by Patiphan-Thiansuwan** [comment]
We used foreman_puppet 6.2.0

**Comment by nadjaheitmann** [comment]
It is part of 6.3.0 at the earliest, so you need to update foreman_puppet for it to work
