### ISSUE TITLE
Test against develop

### ISSUE THREAD

**Issue by ezr-ondrej** [theforeman/foreman_puppet#91]
We are testing against custom branch now, we should switch back to testing against develop as most of the fixes are in the develop now.

**Comment by laugmanuel** [comment]
Should we test our current `master` against `2.5-stable`, then do our release for Foreman 2.5 and then switch to `develop` afterwards?

**Comment by kamils-iRonin** [comment]
> Should we test our current `master` against `2.5-stable`, then do our release for Foreman 2.5 and then switch to `develop` afterwards?

@laugmanuel I believe we can add `2.5-stable` and `develop` both at once. I'll check it and update #139
